force push a timestamp to the base ref branch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/workflows/flowzone.yml b/.github/workflows/flowzone.yml
--- a/.github/workflows/flowzone.yml
+++ b/.github/workflows/flowzone.yml
@@ -483,20 +483,22 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
         run: |
-          out="$(balena-versionist 2>&1)"
-          error="$(awk '/Error:/{getline; print}' <<< "${out}")"
+          # out="$(balena-versionist 2>&1)"
+          # error="$(awk '/Error:/{getline; print}' <<< "${out}")"
 
-          case ${error} in
-            "") # no error
-              ;;
-            'No such file or directory'*'/package.json')
-              echo "::error file=.versionbot/CHANGELOG.yml,line=1::Versionist expects a package.json if repo.yml does not provide a 'type' for the project"
-              ;;
-            *)
-              echo "::error::${error}"
-              exit 1
-              ;;
-          esac
+          # case ${error} in
+          #   "") # no error
+          #     ;;
+          #   'No such file or directory'*'/package.json')
+          #     echo "::error file=.versionbot/CHANGELOG.yml,line=1::Versionist expects a package.json if repo.yml does not provide a 'type' for the project"
+          #     ;;
+          #   *)
+          #     echo "::error::${error}"
+          #     exit 1
+          #     ;;
+          # esac
+
+          date > now
 
           git status --porcelain
 
@@ -588,7 +590,6 @@ jobs:
           echo "sha=$(echo $response | jq -r .sha)" >> $GITHUB_OUTPUT
           echo "json=$(echo $response | jq -c .)" >> $GITHUB_OUTPUT
       - name: Update branch reference
-        if: github.event.pull_request.merged == true && steps.create_commit.outputs.sha != ''
         env:
           GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
         run: |
@@ -601,7 +602,6 @@ jobs:
             -F force=true \
             --include
       - name: Create tag reference
-        if: github.event.pull_request.merged == true && steps.create_tag.outputs.sha != ''
         env:
           GH_TOKEN: ${{ steps.gh_app_token.outputs.token || secrets.FLOWZONE_TOKEN }}
         run: |
